#!/usr/bin/env bash
# Runtime-only Caddy configuration for the bounded dev stack. Uses the
# existing Nix caddy package (pkgs.caddy, available as `caddy` in the
# devShell) but never commits a Caddyfile or key material.
#
# One HTTPS endpoint, loopback-only:
#   https://localhost:18443  -> reverse_proxy 127.0.0.1:18080 (voie-cloud http)
#
# The Fabric API is not fronted by Caddy: fabricd terminates product-shaped
# HTTPS+mTLS itself on the VM-forwarded port, exactly like production.
#
# Every generated byte stays under XDG_RUNTIME_DIR/voie-dev-stack/caddy.
#   gen      create Caddyfile from the live tls material (idempotent)
#   validate static checks + optional `caddy validate` without launching
#   fmt      format check via `caddy fmt` without launching
#
# Only short-lived caddy invocations run here when the binary is present;
# no listener, daemon, VM, or build is started, and no Caddyfile is
# committed to the checkout.
set -euo pipefail

runtime_base="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
case "$runtime_base" in
  /*) ;;
  *) printf 'dev-stack-caddy: XDG_RUNTIME_DIR must be absolute\n' >&2; exit 2 ;;
esac
runtime_root="$runtime_base/voie-dev-stack"
tls_dir="$runtime_root/tls"
caddy_dir="$runtime_root/caddy"
caddy_file="$caddy_dir/Caddyfile"

control_bind="127.0.0.1:18080"
control_listen="18443"

fail() { printf 'dev-stack-caddy: %s\n' "$*" >&2; exit 1; }

require_tls() {
  test -s "$tls_dir/ca.pem" || fail "missing $tls_dir/ca.pem; run dev-stack/tls.sh gen first"
  test -s "$tls_dir/control-cert.pem" || fail "missing control-cert.pem"
  test -s "$tls_dir/control-key.pem" || fail "missing control-key.pem"
}

gen() {
  require_tls
  install -d -m 700 "$caddy_dir"
  # Caddyfile is runtime-only; absolute tls paths keep it hermetic.
  cat >"$caddy_file" <<EOF
{
	admin off
	auto_https off
}

https://localhost:$control_listen {
	tls $tls_dir/control-cert.pem $tls_dir/control-key.pem
	reverse_proxy $control_bind
}
EOF
  chmod 600 "$caddy_file"
  printf 'dev-stack-caddy: wrote %s (control https://localhost:%s -> %s)\n' \
    "$caddy_file" "$control_listen" "$control_bind"
  validate
}

validate() {
  test -s "$caddy_file" || fail "no Caddyfile at $caddy_file; run dev-stack/caddy.sh gen"
  # Static structural checks without launching: no remote hosts, loopback only,
  # expected reverse_proxy targets, tls with absolute runtime paths, mTLS block.
  grep -q "https://localhost:$control_listen" "$caddy_file" || fail "Caddyfile missing control endpoint https://localhost:$control_listen"
  grep -q "reverse_proxy $control_bind" "$caddy_file" || fail "Caddyfile missing control reverse_proxy $control_bind"
  grep -q "tls $tls_dir/control-cert.pem" "$caddy_file" || fail "Caddyfile missing control tls cert path"
  grep -q "admin off" "$caddy_file" || fail "Caddyfile must disable admin"
  # Forbid remote hosts and literal redaction placeholders in the generated file.
  if grep -qE 'REDACTED|__REDACTED|placeholder|example\.com|baremetal' "$caddy_file"; then
    fail "Caddyfile contains forbidden placeholder or remote host"
  fi
  # Optional binary validation without launching any listener.
  if command -v caddy >/dev/null 2>&1; then
    # caddy 2.x fmt takes a bare path (--overwrite/--diff); no --config/--adapter.
    fmt_tmp="$(mktemp "${TMPDIR:-/tmp}/dev-stack-caddy-fmt.XXXXXX")"
    if ! caddy fmt "$caddy_file" >"$fmt_tmp"; then
      rm -f "$fmt_tmp"
      fail "Caddyfile $caddy_file is not canonically formatted; run: caddy fmt --overwrite $caddy_file"
    fi
    if ! cmp -s "$caddy_file" "$fmt_tmp"; then
      rm -f "$fmt_tmp"
      fail "Caddyfile $caddy_file is not canonically formatted; run: caddy fmt --overwrite $caddy_file"
    fi
    rm -f "$fmt_tmp"
    caddy validate --config "$caddy_file" --adapter caddyfile >/dev/null || fail "caddy validate failed for $caddy_file"
    printf 'dev-stack-caddy: caddy validate passed for %s\n' "$caddy_file"
  else
    printf 'dev-stack-caddy: caddy binary not in PATH — static grep checks passed for %s (install pkgs.caddy for full validate)\n' "$caddy_file"
  fi
  printf 'dev-stack-caddy: validated %s\n' "$caddy_file"
}

case "${1:-}" in
  gen) gen ;;
  validate) validate ;;
  fmt) validate ;;
  *)
    printf 'usage: dev-stack/caddy.sh {gen|validate}\n' >&2
    exit 2
    ;;
esac
