#!/usr/bin/env bash
# Start the complete local development stack: PostgreSQL + Blob (dev-cloud),
# local KVM Fabric VM, ephemeral OIDC issuer, built Web artifact, one
# voie-cloud process wired to all of them, plus runtime-only PKI/Caddy
# (HTTPS control + HTTPS Fabric mTLS) and a fixture-only OpenAI-compatible
# model emulator. Every generated byte stays under XDG_RUNTIME_DIR/voie-
# dev-stack; every endpoint is loopback; nothing remote.
#
# Launch through dev-stack/run-scoped.sh so the whole process tree lives in
# one fail-closed systemd user scope. Package installation and frontend
# builds are deliberately NOT done here: provision once via
# `just dev-stack-provision`, then this script consumes the artifacts.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
runtime_base="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
case "$runtime_base" in
  /*) ;;
  *) printf 'dev-stack-up: XDG_RUNTIME_DIR must be absolute\n' >&2; exit 2 ;;
esac
runtime_root="$runtime_base/voie-dev-stack"

scope_name="${VOIE_DEV_STACK_SCOPE:-voie-dev-stack}"
if [[ ! "$scope_name" =~ ^voie-dev-stack(-[A-Za-z0-9]+)?$ ]]; then
  printf 'dev-stack-up: invalid VOIE_DEV_STACK_SCOPE; refusing startup\n' >&2
  exit 2
fi
cgroup_path="$(sed -n 's/^0:://p' /proc/self/cgroup)"
case "$cgroup_path" in
  */"$scope_name".scope | */"$scope_name".slice/*) ;;
  *) printf 'dev-stack-up: refusing to start outside %s.slice; run just dev-stack-up\n' "$scope_name" >&2; exit 2 ;;
esac
# shellcheck disable=SC1091
source "$root/dev-stack/pid-guard.sh"
# A new stack may only begin once every previously owned process is
# verifiably gone: a raced or crashed prior run would otherwise fight this
# run for the VM, the ports, and the aggregate cap. The shared teardown core
# stops leftover scopes and identity-checked pid files without ever
# signalling by raw PID scan, leaves THIS operation's own scope untouched,
# and fails loudly instead of letting survivors slip through.
# shellcheck disable=SC1091
source "$root/dev-stack/teardown.sh"
self_scope="$(basename "$(pid_guard_cgroup "$$")")"
if [[ "${VOIE_DEV_FABRIC_ALREADY_UP:-0}" == 1 ]]; then
  printf 'dev-stack-up: keeping the already-healthy local Fabric VM\n' >&2
else
  if ! stack_teardown "$scope_name" "$runtime_root" \
      "$runtime_base/voie-fabric-dev" "$self_scope"; then
    printf 'dev-stack-up: a previous owned stack did not shut down cleanly; refusing to start\n' >&2
    exit 1
  fi
fi

install -d -m 700 "$runtime_root"
just() { command just --justfile "$root/justfile" "$@"; }

# Bounded compile: Cargo never fans out past two link-heavy jobs here.
cargo_jobs="${VOIE_DEV_CARGO_JOBS:-2}"
case "$cargo_jobs" in
  '' | *[!0-9]*) cargo_jobs=2 ;;
esac
if (( cargo_jobs > 2 )); then cargo_jobs=2; fi

# 1. Cloud data plane (PostgreSQL + Blob). Reuse a healthy stack; start one
# only when its env file or listeners are missing.
env_file="$runtime_base/voie-dev-cloud/env"
pg_port="$(sed -n 's/^export VOIE_DATABASE_URL=.*:\([0-9]*\)\/.*/\1/p' "$env_file" 2>/dev/null || true)"
port_open() {
  local port="${1:-}"
  [[ "$port" =~ ^[0-9]+$ ]] || return 1
  python3 - "$port" <<'PY'
import socket, sys
port = int(sys.argv[1])
s = socket.socket()
s.settimeout(0.3)
try:
    s.connect(("127.0.0.1", port))
except OSError:
    sys.exit(1)
finally:
    s.close()
PY
}
if [[ ! -f "$env_file" ]] || ! port_open "${pg_port:-15432}"; then
  bash "$root/dev-cloud/local-stack.sh" up >/dev/null
fi
env_file="$(bash "$root/dev-cloud/local-stack.sh" env)"
set -a
# shellcheck disable=SC1090
. "$env_file"
set +a
# Local emulator endpoints must be IPv4 path-style. A vanity
# *.blob.localhost name is unroutable here, and rewriting it to
# http://127.0.0.1:PORT with no account path makes Azurite treat Host
# "127.0.0.1" as the account name.
# shellcheck disable=SC1091
source "$root/dev-stack/blob-endpoint.sh"
voie_normalize_local_blob_endpoint

# The Fabric PKI must exist before the VM boots: its server identity and the
# dev CA are handed to the guest read-only, and the host client identity is
# used for every probe. Generation is idempotent.
bash "$root/dev-stack/tls.sh" gen >/dev/null

# 2. Local KVM Fabric VM (C1/C2 substrate). The VM image build is bounded by
# the dev-fabric-build recipe (--max-jobs 1 --cores 2); guest memory is
# pinned to 4 GiB in nix/hosts/fabric-dev.nix so QEMU plus the rest of
# the stack fit the 8G slice cap.
#
# The stack's normal workflow may build the VM artifact on first use: inside
# this scope the existing capped dev-fabric-build path applies (the recipe
# still refuses to run outside voie-dev-stack.slice). Direct
# `just dev-fabric-up` stays conservative and requires an explicit opt-in.
export VOIE_DEV_FABRIC_ALLOW_BUILD=1
if [[ "${VOIE_DEV_FABRIC_ALREADY_UP:-0}" == 1 ]]; then
  printf 'dev-stack-up: local Fabric already up; skipping VM launch\n' >&2
else
  just dev-fabric-up >/dev/null
fi

# 3. Runtime-only PKI (dev CA, control cert, Fabric server cert, Fabric
# client cert/key, CA bundle) under XDG_RUNTIME_DIR — never committed.
bash "$root/dev-stack/tls.sh" gen >/dev/null
tls_dir="$runtime_root/tls"
ca_bundle="$tls_dir/ca-bundle.pem"
control_cert="$tls_dir/control-cert.pem"
control_key="$tls_dir/control-key.pem"
fabric_server_cert="$tls_dir/fabric-server-cert.pem"
fabric_server_key="$tls_dir/fabric-server-key.pem"
client_cert="$tls_dir/client-cert.pem"
client_key="$tls_dir/client-key.pem"

# 4. Prefer the real OpenAI-compatible model configured outside Git. Only an
# explicitly exported provider is honored: there is no repository-adjacent
# environment discovery and no fallback model service. The configured URL is
# normalized into a logical API base because the product probes {base}/models;
# a full chat-completions endpoint must never be handed through as a base.
# Credentials stay in this process: never echoed, never written to stack.env.
model_mode=fixture
real_model_base=""
real_model_key=""
real_model_key_file=""
if [[ -n "${VOIE_MODEL_BASE_URL:-}" && -n "${VOIE_MODEL_API_KEY:-${VOIE_MODEL_API_KEY_FILE:-}}" ]]; then
  real_model_base="${VOIE_MODEL_BASE_URL%%\?*}"
  real_model_base="${real_model_base%%#*}"
  while [[ "$real_model_base" == */ ]]; do
    real_model_base="${real_model_base%/}"
  done
  real_model_base="${real_model_base%/chat/completions}"
  rest="${real_model_base#*://}"
  if [[ ! "$real_model_base" =~ ^https?:// || -z "${rest%%/*}" || -z "$rest" ]]; then
    printf 'dev-stack-up: VOIE_MODEL_BASE_URL must be an http(s) API base, not a full chat-completions URL\n' >&2
    exit 1
  fi
  if [[ -n "${VOIE_MODEL_API_KEY_FILE:-}" ]]; then
    if [[ ! -r "$VOIE_MODEL_API_KEY_FILE" ]]; then
      printf 'dev-stack-up: VOIE_MODEL_API_KEY_FILE is set but unreadable\n' >&2
      exit 1
    fi
    real_model_key_file="$VOIE_MODEL_API_KEY_FILE"
  else
    real_model_key="$VOIE_MODEL_API_KEY"
  fi
  model_mode=real
  real_model_name="${VOIE_MODEL_NAME:-}"
  if [[ -z "$real_model_name" ]]; then
    printf 'dev-stack-up: VOIE_MODEL_NAME is required when using a real provider\n' >&2
    exit 1
  fi
fi

if [[ "$model_mode" != real ]]; then
  # Fixture-only fallback for wiring; C4/C6 explicitly reject this mode. It
  # starts only when no provider is explicitly configured.
  # Reserved: live-c3/c4/c5 use 18087/18084/18085, so the fixture stays on
  # 18083 to avoid BIND collision (see dev-stack/check.sh and tests/live/*).
  model_port="${VOIE_DEV_MODEL_PORT:-18083}"
  model_state_root="$runtime_root/model-fixture"
  model_key_file="$model_state_root/api-key"
  install -d -m 700 "$model_state_root"
  if [[ ! -s "$model_key_file" ]]; then
    printf 'voie-dev-model-key\n' >"$model_key_file"
    chmod 600 "$model_key_file"
  fi
  model_api_key="$(tr -d '\n' <"$model_key_file")"
  if [[ -z "$model_api_key" ]]; then
    printf 'dev-stack-up: model API key file is empty\n' >&2
    exit 1
  fi
  # Start the emulator inside the capped scope; it inherits the slice cgroup.
  if ! curl --fail --silent "http://127.0.0.1:$model_port/healthz" >/dev/null 2>&1; then
    node "$root/dev-stack/model-emulator.mjs" --port "$model_port" --state-root "$model_state_root" --api-key-file "$model_key_file" >"$runtime_root/model-emulator.log" 2>&1 &
    model_pid="$!"
    pid_guard_record "$model_pid" "$runtime_root/model-emulator.pid" "$scope_name" || {
      printf 'dev-stack-up: could not record model emulator ownership; refusing to continue\n' >&2
      exit 1
    }
    for _ in $(seq 1 30); do
      curl --fail --silent "http://127.0.0.1:$model_port/healthz" >/dev/null 2>&1 && break
      sleep 0.5
    done
    curl --fail --silent "http://127.0.0.1:$model_port/healthz" >/dev/null || {
      printf 'dev-stack-up: model emulator did not become ready; log follows\n' >&2
      cat "$runtime_root/model-emulator.log" >&2 || true
      exit 1
    }
  fi
fi

# 5. Ephemeral OIDC issuer with its fixed test account (memory only).
issuer_port="${VOIE_DEV_ISSUER_PORT:-18081}"
issuer_url="http://127.0.0.1:$issuer_port"
if curl --silent "$issuer_url/.well-known/openid-configuration" >/dev/null 2>&1; then
  printf 'dev-stack-up: port %s already serves an OIDC issuer\n' "$issuer_port" >&2
  exit 2
fi
node "$root/dev-stack/oidc-issuer.mjs" "$issuer_port" >"$runtime_root/oidc.log" 2>&1 &
oidc_pid="$!"
pid_guard_record "$oidc_pid" "$runtime_root/oidc.pid" "$scope_name" || {
  printf 'dev-stack-up: could not record OIDC issuer ownership; refusing to continue\n' >&2
  exit 1
}
for _ in $(seq 1 30); do
  curl --fail --silent "$issuer_url/.well-known/openid-configuration" >/dev/null 2>&1 && break
  sleep 0.5
done
curl --fail --silent "$issuer_url/.well-known/openid-configuration" >/dev/null || {
  printf 'dev-stack-up: OIDC issuer did not become ready\n' >&2
  exit 1
}

# 6. Built artifacts the product serves and executes. Startup installs no
# packages and runs no frontend builds; missing artifacts mean one
# provisioning round is owed: `just dev-stack-provision`.
web_root="$root/web/dist"
activation_entry="$root/activation/dist/index.js"
missing=""
test -f "$web_root/index.html" || missing+=" web/dist/index.html"
test -f "$activation_entry" || missing+=" activation/dist/index.js"
if [[ -n "$missing" ]]; then
  printf 'dev-stack-up: missing built artifacts:%s\n' "$missing" >&2
  printf 'dev-stack-up: run just dev-stack-provision once, then retry\n' >&2
  exit 1
fi

# 7. One voie-cloud process over the whole stack. Product env names for
# model and Fabric mTLS are exported here so the control structurally
# reaches both boundaries over HTTPS/mTLS and OpenAI-compatible wiring.
cloud_bind="${VOIE_DEV_CLOUD_BIND:-127.0.0.1:18080}"
# HTTPS control endpoint (Caddy) terminates TLS and reverse-proxies to this http bind.
control_url="https://localhost:18443"
fabric_endpoint="https://127.0.0.1:17840"
export VOIE_BIND="$cloud_bind"
export VOIE_PUBLIC_ORIGIN="$control_url"
export VOIE_OIDC_ISSUER="$issuer_url"
export VOIE_OIDC_ISSUER_URL="$issuer_url"
export VOIE_OIDC_CLIENT_ID=voie-dev
export VOIE_OIDC_CLIENT_SECRET_FILE="$runtime_root/oidc-client-secret"
printf 'dev-only\n' >"$runtime_root/oidc-client-secret"
export VOIE_OIDC_REDIRECT_URL="$control_url/oidc/callback"
export VOIE_WEB_ROOT="$web_root"
export VOIE_ACTIVATION_ENTRY="$activation_entry"
export VOIE_FABRIC_ENDPOINT="$fabric_endpoint"
export VOIE_FABRIC_CLIENT_CERT_PATH="$client_cert"
export VOIE_FABRIC_CLIENT_KEY_PATH="$client_key"
export VOIE_FABRIC_CA_CERT_PATH="$ca_bundle"
# The estate-managed local Fabric: one fixed registry identity, exported
# before launch so the control selects exactly this Fabric. The row itself
# is inserted below, once migrations exist; the identifier is stable across
# stack restarts and overridable only for exotic local setups.
fabric_name="fabric.localhost"
fabric_uuid="${VOIE_DEV_FABRIC_UUID:-00000000-0000-4000-8000-fab1c0000001}"
if [[ ! "$fabric_uuid" =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]; then
  printf 'dev-stack-up: VOIE_DEV_FABRIC_UUID must be a UUID\n' >&2
  exit 2
fi
export VOIE_FABRIC_ID="$fabric_uuid"
# Local-encrypted vault: explicit random key, reused across stack restarts.
secrets_dir="$runtime_root/secrets"
secrets_key_file="$runtime_root/secrets.key"
install -d -m 700 "$secrets_dir"
if [[ ! -s "$secrets_key_file" ]]; then
  (umask 077; openssl rand -hex 32 >"$secrets_key_file")
  chmod 0600 "$secrets_key_file"
fi
export VOIE_USER_SECRETS_BACKEND=local-encrypted
export VOIE_SECRETS_DIR="$secrets_dir"
export VOIE_SECRETS_KEY_FILE="$secrets_key_file"
export VOIE_SECRETS_KEY
VOIE_SECRETS_KEY="$(tr -d '[:space:]' <"$secrets_key_file")"
if [[ ! -f "$secrets_dir/.rekeyed-from-legacy" ]] && compgen -G "$secrets_dir/us-*" >/dev/null; then
  export VOIE_SECRETS_REKEY_FROM_LEGACY=1
fi
if [[ "$model_mode" == real ]]; then
  unset VOIE_FIXTURE_MODEL VOIE_DEV_FIXTURE_MODEL_URL
else
  export VOIE_MODEL_BASE_URL="http://127.0.0.1:$model_port/v1"
  export VOIE_MODEL_NAME="voie-dev-model"
  export VOIE_MODEL_API_KEY="$model_api_key"
  # Explicit fixture label: consumed by tests/live/common.sh:refuse_fixture_model
  # and dev-stack/check.sh to fail C4/C6 closed in fixture mode (C3/C5 can
  # still prove with the emulator after the pickMarker fix).
  export VOIE_FIXTURE_MODEL="1"
  export VOIE_DEV_FIXTURE_MODEL_URL="$VOIE_MODEL_BASE_URL"
fi

cargo build -p voie-cloud --locked --jobs "$cargo_jobs" >/dev/null
if [[ "$model_mode" == real ]]; then
  cloud_model_env=(VOIE_MODEL_BASE_URL="$real_model_base" VOIE_MODEL_NAME="$real_model_name")
  if [[ -n "$real_model_key_file" ]]; then
    cloud_model_env+=(VOIE_MODEL_API_KEY_FILE="$real_model_key_file")
  else
    cloud_model_env+=(VOIE_MODEL_API_KEY="$real_model_key")
  fi
  env "${cloud_model_env[@]}" \
    "$root/target/debug/voie-cloud" >"$runtime_root/cloud.log" 2>&1 &
else
  "$root/target/debug/voie-cloud" >"$runtime_root/cloud.log" 2>&1 &
fi
cloud_pid="$!"
saw_cloud=""
for _ in $(seq 1 50); do
  cur_cmdline="$(tr '\0' ' ' <"/proc/$cloud_pid/cmdline" 2>/dev/null || true)"
  case "$cur_cmdline" in
    *voie-cloud*) saw_cloud=1; break ;;
  esac
  if [[ -z "$cur_cmdline" ]]; then
    break
  fi
  sleep 0.1
done
if [[ -z "$saw_cloud" ]]; then
  printf 'dev-stack-up: voie-cloud did not exec into the product binary\n' >&2
  cat "$runtime_root/cloud.log" >&2 || true
  exit 1
fi
pid_guard_record "$cloud_pid" "$runtime_root/cloud.pid" "$scope_name" || {
  printf 'dev-stack-up: could not record voie-cloud ownership; refusing to continue\n' >&2
  exit 1
}
for _ in $(seq 1 60); do
  if ! pid_guard_validate "$runtime_root/cloud.pid" "$scope_name"; then
    if ! kill -0 "$cloud_pid" 2>/dev/null; then
      printf 'dev-stack-up: voie-cloud exited during startup; log follows\n' >&2
      cat "$runtime_root/cloud.log" >&2 || true
      exit 1
    fi
  fi
  curl --fail --silent "http://$cloud_bind/healthz" >/dev/null 2>&1 && break
  sleep 0.5
done
curl --fail --silent "http://$cloud_bind/healthz" >/dev/null || {
  printf 'dev-stack-up: voie-cloud healthz never became ready; log follows\n' >&2
  cat "$runtime_root/cloud.log" >&2 || true
  exit 1
}
curl --fail --silent "http://$cloud_bind/readyz" >/dev/null || {
  printf 'dev-stack-up: voie-cloud readyz refused (PostgreSQL/migrations)\n' >&2
  exit 1
}

# 7b. Register the estate-managed local Fabric. The registry is estate-
# owned: there is no public Fabric-create API and no user provisioning
# path, so assembly seeds the row itself with the same idempotent insert
# shape as the Ansible control playbook (conflict on name does nothing).
# This runs after readyz proves migrations applied and before any browser
# workspace create can observe an unregistered Fabric. Only the identifier
# and node name are handled here; no secret material passes through or is
# logged.
if ! command -v psql >/dev/null 2>&1; then
  printf 'dev-stack-up: psql not found in PATH; install PostgreSQL client tools (nix develop) and retry\n' >&2
  exit 1
fi
if [[ ! "$VOIE_DATABASE_URL" =~ ^postgres(ql)?://([^:]+):([^@]+)@([^:]+):([0-9]+)/([^?]+)(\?.*)?$ ]]; then
  printf 'dev-stack-up: VOIE_DATABASE_URL has unexpected shape; refusing to continue\n' >&2
  exit 1
fi
_seed_pg_user="${BASH_REMATCH[2]}"
_seed_pg_password="${BASH_REMATCH[3]}"
_seed_pg_host="${BASH_REMATCH[4]}"
_seed_pg_port="${BASH_REMATCH[5]}"
_seed_pg_dbname="${BASH_REMATCH[6]}"
_seed_cred_dir="$runtime_root/.seed-pg-$$"
mkdir -p "$_seed_cred_dir"
chmod 700 "$_seed_cred_dir"
_seed_service_file="$_seed_cred_dir/pg_service.conf"
_seed_pass_file="$_seed_cred_dir/pgpass"
{
  printf '[voie-seed]\n'
  printf 'host=%s\n' "$_seed_pg_host"
  printf 'port=%s\n' "$_seed_pg_port"
  printf 'dbname=%s\n' "$_seed_pg_dbname"
  printf 'user=%s\n' "$_seed_pg_user"
} >"$_seed_service_file"
printf '%s:%s:%s:%s:%s\n' "$_seed_pg_host" "$_seed_pg_port" "$_seed_pg_dbname" "$_seed_pg_user" "$_seed_pg_password" >"$_seed_pass_file"
chmod 600 "$_seed_service_file" "$_seed_pass_file"
# Fail-closed cleanup: secrets leave no trace even if psql fails.
# Expand once so the trap carries the concrete path, not the variables.
# shellcheck disable=SC2064
trap "rm -rf \"$_seed_cred_dir\"; trap - EXIT" EXIT
PGSERVICEFILE="$_seed_service_file" PGSERVICE=voie-seed PGPASSFILE="$_seed_pass_file" psql --set=ON_ERROR_STOP=1 --quiet \
  --command="insert into fabrics (id, name) values ('$fabric_uuid', '$fabric_name') on conflict (name) do nothing" \
  >/dev/null
registered="$(PGSERVICEFILE="$_seed_service_file" PGSERVICE=voie-seed PGPASSFILE="$_seed_pass_file" psql --tuples-only --no-align \
  --command="select exists(select 1 from fabrics where id = '$fabric_uuid')")"
rm -rf "$_seed_cred_dir"
trap - EXIT
unset _seed_pg_password _seed_pg_user _seed_pg_host _seed_pg_port _seed_pg_dbname _seed_service_file _seed_pass_file _seed_cred_dir
if [[ "$registered" != "t" ]]; then
  printf 'dev-stack-up: local Fabric %s is not registered after seeding; refusing to continue\n' "$fabric_uuid" >&2
  exit 1
fi

# 8. Caddy HTTPS/mTLS ingress (control + Fabric) using the existing Nix
# caddy package. Config generation is validated without launching; the
# daemon itself runs inside the capped scope and is torn down with it.
bash "$root/dev-stack/caddy.sh" gen >/dev/null
caddy_bin="${CADDY_BIN:-$(command -v caddy 2>/dev/null || true)}"
if [[ -z "$caddy_bin" ]]; then
  # Nix-provided caddy is available via nixpkgs; devShell adds it, but
  # fall back to `nix run` only for validation — the daemon requires a
  # binary in PATH. This path fails closed rather than building implicitly.
  printf 'dev-stack-up: caddy binary not found in PATH; install pkgs.caddy (nix develop) and retry\n' >&2
  exit 1
fi
"$caddy_bin" run --config "$runtime_root/caddy/Caddyfile" --adapter caddyfile >"$runtime_root/caddy.log" 2>&1 &
caddy_pid="$!"
pid_guard_record "$caddy_pid" "$runtime_root/caddy.pid" "$scope_name" || {
  printf 'dev-stack-up: could not record Caddy ownership; refusing to continue\n' >&2
  exit 1
}
for _ in $(seq 1 30); do
  curl --fail --silent --connect-timeout 2 --max-time 5 --cacert "$ca_bundle" "https://localhost:18443/healthz" >/dev/null 2>&1 && break
  sleep 0.5
done
curl --fail --silent --connect-timeout 2 --max-time 5 --cacert "$ca_bundle" "https://localhost:18443/healthz" >/dev/null || {
  printf 'dev-stack-up: Caddy control HTTPS endpoint did not become ready; log follows\n' >&2
  cat "$runtime_root/caddy.log" >&2 || true
  exit 1
}
# Fabric mTLS endpoint requires client cert verification.
curl --fail --silent --cacert "$ca_bundle" --cert "$client_cert" --key "$client_key" \
  --connect-timeout 2 --max-time 5 \
  "https://127.0.0.1:17840/v1/health" >/dev/null || {
  printf 'dev-stack-up: Caddy Fabric mTLS endpoint did not become ready; log follows\n' >&2
  cat "$runtime_root/caddy.log" >&2 || true
  exit 1
}

{
  echo "VOIE_DEV_STACK_ROOT=$runtime_root"
  echo "VOIE_CONTROL_URL=$control_url"
  echo "VOIE_PUBLIC_ORIGIN=$control_url"
  echo "VOIE_OIDC_ISSUER=$issuer_url"
  echo "VOIE_OIDC_ISSUER_URL=$issuer_url"
  echo "VOIE_OIDC_CLIENT_ID=voie-dev"
  echo "VOIE_TEST_USERNAME=voie-dev"
  echo "VOIE_TEST_PASSWORD=voie-dev-pass"
  echo "VOIE_BROWSER_EXECUTABLE=${VOIE_BROWSER_EXECUTABLE:-chromium}"
  echo "VOIE_CONTROL_CERT_PATH=$control_cert"
  echo "VOIE_FABRIC_ID=$fabric_uuid"
  echo "VOIE_FABRIC_ENDPOINT=$fabric_endpoint"
  echo "VOIE_FABRIC_CLIENT_CERT_PATH=$client_cert"
  echo "VOIE_FABRIC_CLIENT_KEY_PATH=$client_key"
  echo "VOIE_FABRIC_CA_CERT_PATH=$ca_bundle"
  if [[ "$model_mode" == real ]]; then
    echo "VOIE_MODEL_BASE_URL=$real_model_base"
    echo "VOIE_MODEL_NAME=$real_model_name"
  else
    echo "VOIE_MODEL_BASE_URL=http://127.0.0.1:$model_port/v1"
    echo "VOIE_MODEL_NAME=voie-dev-model"
    echo "VOIE_MODEL_API_KEY=$model_api_key"
    echo "VOIE_FIXTURE_MODEL=1"
    echo "VOIE_DEV_FIXTURE_MODEL_URL=http://127.0.0.1:$model_port/v1"
  fi
  echo "VOIE_TLS_CA_BUNDLE=$ca_bundle"
  echo "VOIE_CONTROL_TLS_CERT=$control_cert"
  echo "VOIE_FABRIC_TLS_CERT=$fabric_server_cert"
  echo "VOIE_USER_SECRETS_BACKEND=local-encrypted"
  echo "VOIE_SECRETS_DIR=$secrets_dir"
  echo "VOIE_SECRETS_KEY_FILE=$secrets_key_file"
} >"$runtime_root/stack.env"
if [[ "$model_mode" == real ]]; then
  printf 'local dev stack is up: control %s (https via Caddy -> %s), fabric %s (mTLS -> 127.0.0.1:17840), external model %s, issuer :%s\n' \
    "$control_url" "$cloud_bind" "$fabric_endpoint" "$real_model_name" "$issuer_port"
else
  printf 'local dev stack is up: control %s (https via Caddy -> %s), fabric %s (mTLS -> 127.0.0.1:17840), model http://127.0.0.1:%s/v1 (fixture-only), issuer :%s\n' \
    "$control_url" "$cloud_bind" "$fabric_endpoint" "$model_port" "$issuer_port"
fi

# The launch scope is the lifetime of the stack. Returning would SIGTERM
# QEMU, voie-cloud, Caddy, and the issuer with the transient systemd-run
# unit. `just dev-stack-down` stops that unit.
printf 'dev-stack-up: holding this scope until just dev-stack-down\n'
exec sleep infinity
