//! Derived Application routes. Fabric generates Caddy config; users cannot
//! supply fragments. A route exists only from slug, Environment kind, and
//! the Fabric-owned Service name.

use crate::FabricError;

const KINDS: &[&str] = &["dev", "prod"];

pub struct RouteIntent {
    pub slug: String,
    pub kind: String,
    pub service: String,
}

/// Builds one Host handle inside the :8082 listener. A top-level site
/// block for `{slug}.{kind}.{host}` binds the default HTTP port, so the
/// `:8082` catch-all would win every Host header on the Fabric edge.
pub fn render_route(intent: &RouteIntent, console_host: &str) -> Result<String, FabricError> {
    if intent.slug.is_empty()
        || intent.slug.contains('.')
        || intent.slug.contains('/')
        || intent.slug.contains(' ')
    {
        return Err(FabricError::Config("route slug is not an Application slug"));
    }
    if !KINDS.contains(&intent.kind.as_str()) {
        return Err(FabricError::Config("route kind must be dev or prod"));
    }
    if intent.service.is_empty()
        || intent.service.contains('\n')
        || intent.service.contains('{')
        || intent.service.contains('}')
    {
        return Err(FabricError::Config(
            "route service is not a Fabric Service name",
        ));
    }
    if console_host.is_empty() || console_host.contains('\n') {
        return Err(FabricError::Config("console host is invalid"));
    }
    let matcher = format!("{}_{}", intent.slug.replace('-', "_"), intent.kind);
    Ok(format!(
        "    @{matcher} host {slug}.{kind}.{host}\n    handle @{matcher} {{\n        reverse_proxy {service} {{\n            header_up -X-Voie-Preview-Host\n        }}\n    }}\n",
        slug = intent.slug,
        kind = intent.kind,
        host = console_host,
        service = intent.service
    ))
}

pub fn render_map(intents: &[RouteIntent], console_host: &str) -> Result<String, FabricError> {
    let mut out = String::from(
        "# generated by voie-fabricd; do not edit\n{\n    admin unix//tmp/caddy-admin.sock\n    http_port 8082\n    auto_https off\n}\n:8082 {\n",
    );
    for intent in intents {
        out.push_str(&render_route(intent, console_host)?);
    }
    out.push_str("    handle {\n        respond \"not found\" 404\n    }\n}\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_dev_and_prod_hosts() {
        let text = render_map(
            &[
                RouteIntent {
                    slug: "invoice-demo".into(),
                    kind: "dev".into(),
                    service: "app-invoice-demo-dev:3000".into(),
                },
                RouteIntent {
                    slug: "invoice-demo".into(),
                    kind: "prod".into(),
                    service: "app-invoice-demo-prod:3000".into(),
                },
            ],
            "console.test",
        )
        .expect("renders");
        assert!(text.contains("@invoice_demo_dev host invoice-demo.dev.console.test"));
        assert!(text.contains("@invoice_demo_prod host invoice-demo.prod.console.test"));
        assert!(text.contains("handle @invoice_demo_dev {"));
        assert!(text.contains("header_up -X-Voie-Preview-Host"));
        assert!(text.contains("admin unix//tmp/caddy-admin.sock"));
        assert!(!text.contains("admin off"));
        assert!(text.contains("http_port 8082"));
        assert!(text.contains("    handle {\n        respond \"not found\" 404\n    }\n}\n"));
        assert!(!text.contains("invoice-demo.dev.console.test {"));
        assert!(!text.contains("hostPath"));
    }

    #[test]
    fn rejects_caddy_fragments_in_service() {
        let error = render_route(
            &RouteIntent {
                slug: "ok".into(),
                kind: "dev".into(),
                service: "x { import evil }\n".into(),
            },
            "console.test",
        );
        assert!(error.is_err());
    }
}
